### ISSUE TITLE
Attio for CRM instead of HubSpot

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/partnerships#101]
This founder is experienced with web3 outreach, his venture backed business essentially is this for developer relations. 

- Research Attio and see if its a good fit for our needs. 
- Highlight disadvantages that this has compared to HubSpot in the context of our needs. 
- https://attio.com/

> Alex | Ubiquity DAO, [Dec 11, 2024 at 22:26]
> yea we are just setting up our outreach campaigns again
> 
> Alex | Ubiquity DAO, [Dec 11, 2024 at 22:26]
> email/linkedin/x/telegram i guess
> 
> rick, [Dec 11, 2024 at 22:26]
> I recommend just writing scripts yourselves in the relevant groups
> 
> rick, [Dec 11, 2024 at 22:27]
> And save the money use a simple CRM
> 
> rick, [Dec 11, 2024 at 22:27]
> I’m using Attio right now
> 
> rick, [Dec 11, 2024 at 22:27]
> But since you are very web3 focused it might be a good investment
> 
> Alex | Ubiquity DAO, [Dec 11, 2024 at 22:27]
> there was one feature that they had that seems sooo useful though, it was basically perfect for pre conference automated  outreach to set up meetings en masse
> 
> Alex | Ubiquity DAO, [Dec 11, 2024 at 22:27]
> we just set up hubspot
> 
> rick, [Dec 11, 2024 at 22:27]
> Haha I hate hubspot so much
> 
> Alex | Ubiquity DAO, [Dec 11, 2024 at 22:27]
> never heard of this but thanks for the tip. is it just better cause of cost?
> 
> rick, [Dec 11, 2024 at 22:27]
> Never going to touch that thing again
> 
> rick, [Dec 11, 2024 at 22:27]
> 😂
> 
> Alex | Ubiquity DAO, [Dec 11, 2024 at 22:28]
> i dont use crms often enough to have strong opinions
> 
> Alex | Ubiquity DAO, [Dec 11, 2024 at 22:28]
> i used google sheets for a long time lol
> 
> rick, [Dec 11, 2024 at 22:28]
> It’s a new CRM, fresh design leaner etc
> 
> rick, [Dec 11, 2024 at 22:28]
> https://attio.com/
> 
> Alex | Ubiquity DAO, [Dec 11, 2024 at 22:28]
> I'll have the guys look at it
> 
> rick, [Dec 11, 2024 at 22:28]
> We are rebuilding most of our features based on their CRM logic
> 
> rick, [Dec 11, 2024 at 22:29]
> For our own platform
> 
> rick, [Dec 11, 2024 at 22:29]
> Quite a big inspiration
>

**Comment by v4d33m** [comment]
heard about it. let me look into it.

**Comment by 0x4007** [comment]
- I made a proposal today about improving the task limiter which will solve for this scenario I think https://github.com/ubiquity-os-marketplace/command-start-stop/issues/103

However, now that you are a collaborator, technically you can use the GitHub UI to self assign and circumvent. In the short term feel free to do this, until we ship the fix.

**Comment by v4d33m** [comment]
from the first glance - i kinda like it. looks quite flexible. it's like someone took airtable and spent a lot of time creating numerous presets.

**Comment by v4d33m** [comment]
So below I'm going to do an apples-to-apples comparison between Attio and Hubspot. 
Here are the criteria/goals:
1) UX -> should keeping visual noise to minimum. How visually appealing it is? How easy it is to set up necessary views, change forms? How does companies, contacts and deals appear? 
2) Deal logic - we need to set up two pipelines (Investors and Partners), we should be able to enroll companies in both pipelines and associate with different contacts within one company. 
3) Dashboards - how easy it is to set up dashboards? how informative those dashboards are?  
4) Import/export - upload a csv export list from Clay to Attio/Hubspot.
5) Integrations - can we integrate the rest of our martech stack into it to make sure that no info is lost? 
6) Pricing.

**Comment by v4d33m** [comment]
UX

Attio looks more modern and appealing (very subjective, but i like it). It has copied notion design and airtable logic.  
![Screenshot 2024-12-11 at 9 38 44 PM](https://github.com/user-attachments/assets/81baf17a-a20c-43f9-8cb3-fccec9b57b5a)
Hubspot has more "enterprisey" look with very crowded menu - objectively, learning curve into that system would be more steep
![Screenshot 2024-12-11 at 9 52 04 PM](https://github.com/user-attachments/assets/499139e9-f17f-4c76-a629-952f48ef75e7)

Companies list in Attio is very much similar to airtable/google sheets, it's quite easy to set up new properties  
![Screenshot 2024-12-11 at 9 54 47 PM](https://github.com/user-attachments/assets/988373bb-aed2-4837-9ef4-98f7b1f23f83)
However, there are several things that Attio is missing: 
1) Company ownership. There is an attribute "created by" that is closest to it, however, if you would need to change the ownership of a specific company - there is no way to do it 

2) Very limited activity feed functionality 
![Screenshot 2024-12-11 at 9 59 11 PM](https://github.com/user-attachments/assets/664bcf85-c989-4fe7-a1e2-417195b16d2b)

3) You can't change properties in the "create a company" form. there is a template functionality, maybe it could work, but it's literally empty
![Screenshot 2024-12-11 at 10 07 57 PM](https://github.com/user-attachments/assets/0c0da7ac-7104-4bb1-a7dc-2b00ff9408d8)

Hubspot has very standard view for companies, you can set up any properties or views that you want. It would take some time to do it, but when it's done it would be there forever. 
![Screenshot 2024-12-11 at 10 15 31 PM](https://github.com/user-attachments/assets/af8a4916-62ac-463d-bcd3-75a552c2fdb0)

Exactly same problems with people aka contacts in Attio. No ownership, strange set of properties, very limited functionality. 

Conclusion: Attio has better UI than Hubspot but UX-wise there is still a lot to improve. I would say they are on par.

**Comment by v4d33m** [comment]
** DEAL LOGIC ** 

There are no deals in Attio. Instead of Pipelines in Attio there are lists. You can create as many as you need and add companies. You can add different views in list/kanban mode and kanban view for the list is the closest you can get to recreate pipelines. 
![Screenshot 2024-12-11 at 10 26 20 PM](https://github.com/user-attachments/assets/73c036d6-9b3d-43bc-b817-a61ae7c9b12e)
They have a lot of presets, but they don't have anything resembling our partnership deal flow. Creating a list with a set of views would be a separate and quite tedious task. I should probably reconsider my statement about steep learning curve.  
![Screenshot 2024-12-11 at 9 38 23 PM](https://github.com/user-attachments/assets/feb7e722-a8b6-4700-b489-45a9bd98928c)

Also, there is one blocking issue with Attio: 
- you can enrol a company in two lists, but since there are no deals, you can't have different contacts associated with that specific opportunity - you would have dig into the whole list of people to understand who you have to deal with. 

Also, in term of deal/task tracking Attio is very limited.

**Comment by v4d33m** [comment]
Dashboards - Creating dashboards in Attio take much more time, reports out of the box are not really informative. To set up a similar dashboard that we have in HS would take time well beyond the scope of that task. I also realised that there are no week-to-week comparisons (or i couldn't easily find those) 
![Screenshot 2024-12-11 at 10 40 16 PM](https://github.com/user-attachments/assets/7b6ef0ad-c66e-4ff5-9e2b-7131449c560e)
![Screenshot 2024-12-11 at 10 41 47 PM](https://github.com/user-attachments/assets/2dfbf654-adad-47bd-a1e9-ff50c4e37b32)

**Comment by v4d33m** [comment]
Import / export

Import in Attio simply doesn't work. It requires perfect formatting and event with this Attio managed to import phone numbers twice in the same field that would not allow to call. 

Here are screenshots with my failed attempts: 

![Screenshot 2024-12-11 at 6 36 44 PM](https://github.com/user-attachments/assets/a1f6d50e-eeac-4f42-93f4-1feb8cf432e2)
![Screenshot 2024-12-11 at 9 34 09 PM](https://github.com/user-attachments/assets/77924b4f-24e1-4f3f-8730-2700f106b759)
![Screenshot 2024-12-11 at 9 34 01 PM](https://github.com/user-attachments/assets/5a6cbd88-5eb0-482e-8337-1390491995b8)
![Screenshot 2024-12-11 at 10 59 31 PM](https://github.com/user-attachments/assets/a4d6c8cd-7ab1-4676-a12d-6d0fbaffad98)

Import in HubSpot could also be quite tedious (mapping issues and way too many preconfigured properties). But at least, you always have there a little widget that would tell you what's wrong with your data. 
![Screenshot 2024-12-11 at 10 59 41 PM](https://github.com/user-attachments/assets/ec790b5e-ecbd-4f87-b40b-a1140698d63e)
![Screenshot 2024-12-11 at 10 59 59 PM](https://github.com/user-attachments/assets/f0db4547-c6a1-4ff1-8d8e-398b6b8586ba)

**Comment by v4d33m** [comment]
**integrations**

Hubspot integrates with everything in this world. Especially, our stack: 
Heyreach
![Screenshot 2024-12-11 at 11 20 13 PM](https://github.com/user-attachments/assets/3e7ffbfe-1365-4e3a-8da4-eccaa40a6b39)
Smartlead
<img width="1429" alt="Screenshot 2024-12-11 at 6 05 29 PM" src="https://github.com/user-attachments/assets/0a5ac906-35b7-4c5f-b376-273e9fedf526" />
and also telegram through respondi.io

Attio integrates with the following tools (that we don't have): 
<img width="808" alt="Screenshot 2024-12-11 at 6 05 48 PM" src="https://github.com/user-attachments/assets/ed431fe4-8190-4b20-9ce0-6bd806e82394" />

**Comment by v4d33m** [comment]
and the last - pricing. 

Unless we aim at the "free tier" Hubspot wins as well. Paid tiers at Attio start with $34/user/month instead of $20/user/month in Hubspot.

For $69 a month we can get also a tier with a lot of enrichment options, but i doubt that this enrichment could ever beat clay.


My final recommendation: 
I would not switch to Attio unless i'm held at gunpoint. There are no advantages over hubspot apart from being slightly more visually appealing.

**Comment by v4d33m** [comment]
PS. There is no SEARCH for people in Attio. c'mon that's hygiene.

**Comment by v4d33m** [comment]
@0x4007 please accept

**Comment by v4d33m** [comment]
btw , there are a couple of other "NEXT GEN CRMs" we might be considering: 
https://www.folk.app/
https://www.breakcold.com/

**Comment by 0x4007** [comment]
@minhyeong112 rfc (request for comment)

**Comment by minhyeong112** [comment]
Completely agree with @v4d33m 's thorough comparative analysis.  In my limited experience with HubSpot, I already saw the benefits that he mentioned (including the bot that makes fixes to your imports).  

Also, Convrt.ai supposedly has telegram automation and HubSpot integration.  (I haven't personally tested it, but they say that they can do both) So that's another small potential benefit to sticking with HubSpot: having potential access to another Telegram automation option.

**Comment by 0x4007** [comment]
> ```diff
> ! Issue is non-collaborative. Skipping permit generation.
> ```

@gentlementlegen notes:
- If there is no pull request, then the "payouts mode" should accomodate non coding tasks like this one. 
- Admin or billing manager should be exempt.

Also if you don't mind trying to regenerate the permits that would be appreciated!
