### ISSUE TITLE
Partnership: MakerDAO  - SubDAO Collaboration Proposal

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/partnerships#11]
It looks like other organizations in the ecosystem are contributing technologies and operations in a decentralized manner to MakerDAO. I think this could be an interesting opportunity to introduce ourselves and be of service to MakerDAO via the DevPool. They seem to be excited about decentralized organizations, increasing operational efficiencies, and AI for all of this. The UbiquiBot seems to check the boxes. 

Make an introduction on their forum and try and become a partner of MakerDAO, primarily by means of sharing our technologies. 

I noticed that BA Labs introduced themselves on all the SubDAO forums. [zero](https://forum.makerdao.com/t/zero-professional-ecosystem-actor-introduction-ba-labs/20814), [one](https://forum.makerdao.com/t/one-professional-ecosystem-actor-introduction-ba-labs/20818), [two](https://forum.makerdao.com/t/two-professional-ecosystem-actor-introduction-ba-labs/20815), [three](https://forum.makerdao.com/t/three-professional-ecosystem-actor-introduction-ba-labs/20819), [four](https://forum.makerdao.com/t/four-professional-ecosystem-actor-introduction-ba-labs/20820), [five](https://forum.makerdao.com/t/five-professional-ecosystem-actor-introduction-ba-labs/20821).

I also want to highlight Rune (founder's) vision for additional context: 
1. https://twitter.com/RuneKek/status/1656731619753852951
2. https://forum.makerdao.com/t/the-5-phases-of-endgame/20830

He wants AI to be used in facilitation, not decision making, which makes sense. 

> This is an important point and something that is core to the design. The key will be to not have AI actually “run” governance, but just use it as a redundant assistant tool that is especially optimized to help participants that are more on the periphery of the ecosystem, and aren’t necessarily able to spend full time diving into the deep nuances of Maker Governance. With Governance AI Tools they have a chance to find out what’s going on, and be directed towards which areas they should be focusing because there is more critical data or controversy. Ultimately, in case of significant internal failure the Governance AI Tool may alert outsiders to wrongdoing or negligence by insiders that are operating within areas that would normally be completely obscured due to complexity, so they enable a lot more parallelization and specialization without putting governance security at risk.
> 
> Actual decisions should be done by domain experts, primarily the Advisory Council Members, but AI tools can be a massive productivity boost by helping them dealing with paperwork, reporting, and formatting everything correctly according to the Alignment Artifact data structure, so they can focus just on being subject matter experts and don’t have to wrangle with governance complexity.
> 
> False positives can be dealt with by ensuring that the AI tools are never relied on as the source for any decision, but that they simply help with automating boring work or paperwork, and are used to get suggestions for where to direct attention or how to learn about an advanced concept. 

[Source](https://forum.makerdao.com/t/the-5-phases-of-endgame/20830/5)

## Appendix
1. https://t.me/UbiquityDAO/29361/30020

**Comment by pavlovcik** [comment]
@Hodlatoor check this out

**Comment by Hodlatoor** [comment]
🫡

**Comment by Hodlatoor** [comment]
@pavlovcik 
https://www.notion.so/ubiquitydao/Hello-MakerDAO-4d2ba99dcf68494a91d2fe1ff7784c9f

**Comment by 0x4007** [comment]
You should start using pull requests in order to fully integrate with our system. So basically you can use this repository a little like "Google Docs" and make directories and post markdown documents as your pull request. Once the pull request is merged, the bot will automatically credit you for the work. 

If you want to do this strictly through he GitHub UI you can navigate to https://github.com/ubiquity/partnerships/new/development from 
<img width="1257" alt="image" src="https://github.com/ubiquity/partnerships/assets/4975670/48d452c7-b877-4d38-a782-debc6a27719f">

However I encourage you to use the best tooling available for text editing, with its built-in Git support, which is vscode!

**Comment by Hodlatoor** [comment]
https://forum.makerdao.com/t/professional-ecosystem-actor-intro-devpool/20894
