### ISSUE TITLE
OnlyDust

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/partnerships#15]
Get our bounties on here!

https://app.onlydust.xyz/

**Comment by Draeieg** [comment]
Contacted them on

their feedback form
their twitter
a DM to their CTO on twitter

**Comment by Draeieg** [comment]
![Screenshot_20230607_232820_Gmail.jpg](https://github.com/ubiquity/partnerships/assets/88983138/642a01da-6902-4add-8358-bbf9f20a128d)

Got a reply via Email, this is the current status

**Comment by 0x4007** [comment]
Perhaps you should try hunting them down on Telegram, Twitter, and Discord.

**Comment by pavlovcik** [comment]
Hey @Draeieg you should keep providing updates if you want to keep working on this bounty.

**Comment by 0x4007** [comment]
Perhaps it makes sense to just roll this in to #28

**Comment by Draeieg** [comment]
![IMG_20230616_151250_284.jpg](https://github.com/ubiquity/partnerships/assets/88983138/2e06d7b5-ac15-4901-9157-777d378270e8)
