### ISSUE TITLE
Connect with MakerDAO directors

### ISSUE THREAD

**Issue by Hodlatoor** [ubiquity/partnerships#24]
We want to create traction within MakerDAO for DevPool integration.
Your task is to connect with the directors at the DAO and have them provide feedback on our proposal:
https://forum.makerdao.com/t/professional-ecosystem-actor-intro-devpool/20894

definition of feedback :
commentary from at least 2 out of the 5 members (list all 5 members you found and provide their feedback in the form of a link on the makerdao forum or screenshots from other channels)

**Comment by 0x4007** [comment]
I think that you should explicitly list the five members you're referring to in order to make this bounty clear.

**Comment by 0x4007** [comment]
I can raise the base rate on this repo to make the bounties higher. I'll get to that when I go to my computer in a bit.
