### ISSUE TITLE
Inbound Recruiting: Find

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/partnerships#27]

**Comment by sergfeldman** [comment]
> @sergfeldman The time limit for this bounty is on Thu, 15 Jun 2023 13:42:19 GMT

@pavlovcik Compiling the list of websites will take at least a few days.

**Comment by 0x4007** [comment]
@0xcodercrane why is the bot ignoring @diamondnegroni

**Comment by cuddle-dev** [comment]
> @0xcodercrane why is the bot ignoring @diamondnegroni

It might be throwing in schema validation of @diamondnegroni 's github profile. I am seeing he is a new GitHub user.

**Comment by 0x4007** [comment]
Should we file an issue for that?

**Comment by diamondnegroni** [comment]
https://github.com/ubiquity/ubiquibot/issues/430

**Comment by diamondnegroni** [comment]
1 | https://hackenproof.com/
2 | https://immunefi.com/
3 | https://www.yeswehack.com/
4 | https://bugbounty.jp/en/
5 | https://bountysource.com/
6 | https://bounties.network/
7 | https://frontal.io/services/bug-bounty-platform/
8 | https://issuehunt.io/
9 | https://sourcecred.io/
10 | https://bugrap.io/
11 | https://bounty0x.io/
12 | https://www.cryptoknowmics.com/bounty
13 | https://www.synack.com/
14 | https://www.bugcrowd.com/
15 | https://tokenminds.co/bounty-campaign-marketing/
16 | https://www.cypherhunter.com/en/
17 | https://thebugbountyhunter.com/
18 | https://www.gitcoin.co/
19 | https://huntr.dev/
20 | https://ctf365.com/
21 | https://www.intigriti.com/
22 | https://firebounty.com/
23 | https://www.hackerone.com/product/bug-bounty-platform
24 | https://www.codementor.io/
25 | https://fundition.io/
26 | https://www.fiverr.com/
27 | https://www.toptal.com/
28 | https://www.freelancer.com/
29 | https://www.upwork.com/
30 | https://www.freelancermap.com/
31 | https://www.peopleperhour.com/
32 | https://www.guru.com/
33 | https://www.openbugbounty.org/
34 | https://ctftime.org/event/list/upcoming
35 | https://bitcointalk.org/index.php?board=238.0
36 | https://t.me/token2049official
37 | https://t.me/polygonkorea
38 | https://t.me/TokyoSocialHH
39 | https://www.bugbountyhunter.com/
40 | https://bugrap.io/

**Comment by 0x4007** [comment]
I think that theres some items that can't be credited for. We only want websites, not Telegram groups. This is because Telegram groups usually will ban you from recruiting/spamming. 

Also some of these seem to be security focused, which is suboptimal but acceptable. We want to do more generalized bounty boards for builders, not just security auditors.

Lastly, please submit using our new "[non code deliverables process](https://dao.ubq.fi/non-code-devpool-deliverables-process)" - it's a bit rough now but it allows us to standardize the review and later, audit process.

**Comment by 0x4007** [comment]
Check this https://sovs.notion.site/sovs/Sov-s-Compendium-41f097d28dae4d09801f10cde1b2d03b

**Comment by diamondnegroni** [comment]
Do you know why 200 WXDAI is not claimable? It says THIS PERMIT IS NOT CLAIMABLE
@sergfeldman @pavlovcik

**Comment by 0x4007** [comment]
Because you already claimed it. https://gnosisscan.io/tx/0x921463139aaaeb77870946b58da7113a1d5e493ec9a1440b7541a5e2eef95695
