### ISSUE TITLE
Confirm news coverage

### ISSUE THREAD

**Issue by Hodlatoor** [ubiquity/partnerships#36]

**Comment by 0x4007** [comment]
I still don't understand why this was necessary to do.

**Comment by Hodlatoor** [comment]
as jin commented:

This is traditional way of how institutionals PR do which I think it's a
great way to build trackrecord to the public. 🧳🧳💼💼

**Comment by 0x4007** [comment]
Yes but we discussed this too many times to count already. My stance never changed on this. Press coverage is not a priority.

**Comment by Hodlatoor** [comment]
Sure And as we said, we have different experience sets on that. flexibility
on both ends towards the middle will be more synergistic.

**Comment by Hodlatoor** [comment]
https://www.ibtimes.sg/ubiquity-dao-taking-crypto-project-0-200-million-70745
