### ISSUE TITLE
review specs around aug 9th for full grant council outline.

### ISSUE THREAD

**Issue by Hodlatoor** [ubiquity/partnerships#37]
https://safe-global.notion.site/Safe-Grants-7a14a7403f1f44f0bfb236a7521dac91

supposed to be live by today but is not. waiting on them.

**Comment by 0x4007** [comment]
Can you provide more context on this?

**Comment by Hodlatoor** [comment]
They had a vector for early submission which we did and then there is a
longer one for the grants which they haven't made public yet

**Comment by Hodlatoor** [comment]
They have still not opened up the full grant as of 7/10

**Comment by Hodlatoor** [comment]
new date announced. July 27th opens for submissions. updated the issue accordingly

**Comment by 0x4007** [comment]
> new date announced. July 27th opens for submissions. updated the issue accordingly

Looks like its time to submit!

**Comment by Hodlatoor** [comment]
They pushed it back: Wave 1 Safe grants applications will open on the 09.08.2023.

**Comment by 0x4007** [comment]
> 09.08.2023.

Can you use unambiguous notation in the future e.g. 9 August 2023? It would be helpful if you also cite your source. 

Looking forward to progress with Gnosis
