### ISSUE TITLE
Ways of VC engagement

### ISSUE THREAD

**Issue by sergfeldman** [ubiquity/partnerships#46]
**The goals of this research:**
1. To find out VCs priorities and contact options.
2. Define Ubiquity approach for contacting VCs.

Potential research next steps
- Look for the insiders
- Search on how to get investment from (VC name), how to contact, events, programs
- Define suitable for us online and offline crypto VC events
- Create a plan for participation in the events 

### Proposed approach

Realize the investment priorities of each VC and position Ubiquity accordingly while communicating with this VC.

**Target audience groups**
Ubiquity bank primarely targets Web3 native individuals, not business and not normies.

DevPool targets mature Open Source projects that are building on GitHub, and developers-freelancers.

**Product vision**
Ubiquity is building a freelance marketplace embedded into GitHub and a stablecoin to power overall Ubiquity ecosystem.

In the future, we plan to create an ecosystem where Web3 natives can earn from freelancing and DeFi, as well as conveniently manage their finances.

### Ways of VC engagement 

- Introductions from insiders.
- VC products, programs, competitions.
- Accelerators and startup schools.
- Online and offline crypto events.

### 1. Introductions from insiders

Alex connections.
TBD

### Paradigm

>"https://www.paradigm.xyz/
Paradigm is a **research-driven technology** investment firm
We invest in, build, and contribute to companies and protocols with as little as $1M and as much as $100M+. We often get involved at the earliest stages and continue to support our portfolio companies over time.
We take a deeply hands-on approach to help projects reach their full potential, from the technical (mechanism design, security, engineering) to the operational (recruiting, go-to-market, legal and regulatory strategy)."

**Ubiquity position for the beginning of communication**
TBD

**How to contact**

- Contact via website 
https://www.paradigm.xyz/contact

- Any other ideas on how to reach out to them?

### GnosisDAO

>Investement strategy TBD

**Ubiquity position for the beginning of communication**
- Focus on Ubiquity as a bank on top of Safe.
Highlight security and safety features, as well as more features that enrich Safe usage.
Became Safe ambassadors - for example, grant Safe wallet for top bounty hunters.
- Do not focus attention on DevPool at the beginning.

**How to contact**

- [ ] Participate in Core Devs calls

https://www.gnosis.io/blog/gnosis-core-devs-call-notes-may-17-2023

- [x] ubiquity/partnerships#47
https://discord.com/invite/gnosischain

- [ ] Contact them through the forum, apply for the grant 
https://forum.safe.global/

- [ ] Add Ubiquity to the Safe apps marketplace
https://app.safe.global/apps
https://docs.safe.global/discover/built-on-safe

- [ ] Review integration Safe + cards 
Monerium is a company regulated in Iceland
https://monerium.com/guides/safe/

- [ ] Come to their events 
https://coindar.org/en/coin/gnosis-gno

### Microsoft/GitHub

>"Microsoft M12
https://fortune.com/2023/03/03/microsoft-venture-m12-new-strategy-employees-left/
https://blogs.microsoft.com/blog/2023/01/05/m12-ventures-down-a-new-path/
https://www.businessinsider.com/microsoft-m12-venture-arm-strategy-pay-change-2023-5
"The turmoil was sparked when M12 changed from a model similar to an independent venture fund focused on backing startups with the best potential for a return on investment, to a more traditional corporate venture fund focused on making investments that help boost Microsoft's ecosystem."

>GitHub core value is collaboration on software.

**Ubiquity position for the beginning of communication**
- Focus on DevPool because its facilitates Open Source development and community engagement.
- Do not focus attention on the crypto products and flows.

**How to contact**

- Apply and participate in the Microsoft accelerator 
https://www.microsoft.com/MEA/startups/growthxaccelerator/
https://www.microsoft.com/en-us/startups
https://foundershub.startups.microsoft.com/signup

- Contact Microsoft M12 fund
https://m12.vc/focus/web3-metaverse-gaming/
https://twitter.com/m12vc
https://m12.vc/news/announcing-the-m12-github-fund/
https://blogs.microsoft.com/blog/2023/01/05/m12-ventures-down-a-new-path/
https://www.crunchbase.com/organization/microsoftventures

- Participate in the GitHub accelerator
We can apply in the next wave, but the focus is on the Open Source projects
https://accelerator.github.com/
https://accelerator.github.com/#committee - current participants, requirements, committee 
https://github.blog/2022-11-09-an-open-source-economy-built-by-developers-for-developers/
https://github.blog/2023-04-12-github-accelerator-our-first-cohort-and-whats-next/
https://www.youtube.com/watch?v=HH3Frl2_e80

- Add DevPool to GitHub docs
For example, the doc about encouraging contributions 
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/encouraging-helpful-contributions-to-your-project-with-labels
How to update GitHub docs
https://github.com/github/docs/blob/main/CONTRIBUTING.md
We can take as an example the documentation on funding where non-GitHub resources are listed
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

- Tag GitHub leaders to send them notifications
Naytri Sramek - Senior Director GitHub
https://github.com/naytri

### Visa, MasterCard

>Visa 
https://www.cbinsights.com/research/visa-strategy-map-investments-partnerships-acquisitions/
Interested in payments everywhere.
TBD

>MasterCard 
https://newsroom.mastercard.com/news/perspectives/2023/earnings-review-on-strategy-and-for-growth/
https://www.mastercard.com/news/perspectives/2023/mastercard-annual-ceo-letter/
TBD

**Ubiquity position for the beginning of communication**
- Probably focus on payments for a new for them group - developers on GitHub.
- TBD

**How to contact**

- Participate in Visa events 
https://investor.visa.com/events-calendar/default.aspx

- Participate in Visa programs for startups
https://visainnovationprogram.com/
https://www.visa.com.sg/visa-everywhere/innovation/apaccelerator.html
https://partner.visa.com/site/programs/fintech-program.html
https://usa.visa.com/visa-everywhere/everywhere-initiative/initiative.html
https://partner.visa.com/
Fast track - apply with info on the registration and funding
Idea - mostly socially important projects took grants in 2022

- Participate in MasterCard programs for startups 
https://developer.mastercard.com/programs/start-path-crypto/
https://developer.mastercard.com/programs/
https://vc4a.com/mastercard-foundation/smart-path-small-business-program/
https://www.f6s.com/mastercardstartpathglobal/apply

### Coinbase Ventures

>"Mission https://www.coinbase.com/ventures
We back exceptional entrepreneurs working to advance the crypto/Web3 ecosystem and support Coinbase’s mission of **creating more economic freedom** for the world.
We partner with founding teams at the earliest stages, and invest broadly across all categories within the cryptoeconomy.
We have invested in hundreds of teams building everything from layer 1 protocols, Web3 infrastructure, centralized on-ramps, decentralized finance, NFTs, metaverse technologies, developer tooling, and more. 
We strive to be strategic partners for founders and take a collaborative approach to investing. We support founders through operational experience, distribution, strategic partnerships, and more."

>The strategy of the Base - gateway to Web3.

**Ubiquity position for the beginning of communication**
- Focus on economic freedom that the entire Ubiquity ecosystem can bring.
- Potentially, focus on DevPool service for the Base ecosystem growth.

**How to contact**

- Build on Base
https://base.org/

- TBD

### 3. Accelerators and schools

https://a16zcrypto.com/crypto-startup-school/

https://alliance.xyz/apply

### 4. Online and offline crypto events

**Lists**
https://www.web3native.co/crypto-web3-events Events and grants
https://cointelegraph.com/events
https://www.web3-event.com/crypto-events
https://www.nfttech.com/events
https://ninjapromo.io/best-crypto-conferences

**Top events**

TBD

**Comment by 0x4007** [comment]
> Come to their events
https://coindar.org/en/coin/gnosis-gno

Co-hosting hackathons seems like a really cool idea, and leveraging our Ubiquibot for payouts etc seems like a low friction and high value-add partnership? 

https://twitter.com/encodeclub/status/1649125839227826176

@Draeieg

**Comment by 0x4007** [comment]
You might be able to make each lead a bounty e.g. GnosisDAO, Paradigm etc. with a task specification of all the suggested forms of outreach.
