### ISSUE TITLE
Content

### ISSUE THREAD

**Issue by Hodlatoor** [ubiquity/partnerships#60]
create outline for content narrative. 
create content google slide deliverable. 
target audience is business decision makers as opposed to mid-level operators.

**Comment by Hodlatoor** [comment]
@pavlovcik can you set the labels

**Comment by Hodlatoor** [comment]
good timing! take a look:
https://docs.google.com/presentation/d/19PqMLGvkwv0MwF0ej5ip7XlwfFM8a0RHJ0V0g62pUcI/edit?usp=sharing

**Comment by 0x4007** [comment]
I was writing this comment while you were working on this

https://github.com/ubiquity/business-development/issues/58#issuecomment-1636988085

The deck writing should be more concise.

Can you add comment access (or just edit access for anybody with the link) to the slides?

**Comment by Hodlatoor** [comment]
> I was writing this comment while you were working on this
> 
> https://github.com/ubiquity/business-development/issues/58#issuecomment-1636988085
> 
> The deck writing should be more concise.
> 
> Can you add comment access (or just edit access for anybody with the link) to the slides?
> 
> 

edit Access enabled. It's five pages quite concise and focused imo.

**Comment by Hodlatoor** [comment]
> I was writing this comment while you were working on this
> 
> https://github.com/ubiquity/business-development/issues/58#issuecomment-1636988085
> 
> The deck writing should be more concise.
> 
> Can you add comment access (or just edit access for anybody with the link) to the slides?
> 
> 

One important thing to keep in mind with C level documents, They are typically do not read linearly. people jump and skim so that's why highlights and bold font as well as repeating content in strategic places is important.

**Comment by Hodlatoor** [comment]
closed via gituhub android app but didn't see ubiquibot pop in. re-opening and closing on desktop

**Comment by Hodlatoor** [comment]
testing ubiquibot

**Comment by Hodlatoor** [comment]
@pavlovcik questions:
1. ubiquibot wasn't invoked when closed from github android app?
2. update: didn't see payment link generated from ubiquibot above while on mobile. seeing it now.

**Comment by 0x4007** [comment]
> good timing! take a look:
> https://docs.google.com/presentation/d/19PqMLGvkwv0MwF0ej5ip7XlwfFM8a0RHJ0V0g62pUcI/edit?usp=sharing

I have mixed feelings with the URL being posted as the deliverable because the link can be broken and can complicate auditing this task in the future. Perhaps it makes the most sense to deliver the content in a markdown document via a pull request and associate with this issue.

**Comment by Hodlatoor** [comment]
This also was completed. What is going on?
