### ISSUE TITLE
Xmas party & Recruitment event in Korea

### ISSUE THREAD

**Issue by diamondnegroni** [ubiquity/partnerships#67]
Goals:
1. Establish collaborations with key foundations and blockchain clubs at renowned universities in Korea.
2. Promote Ubiquity DAO by showcasing the capabilities of the GitHub Bot and Devpool.
3. Expand the development pools, aiming to attract TypeScript and Solidity developers from Korea.

Deliverables 
1. Identify and engage with 5 foundations for event hosting or sponsorship.
2. Develop and launch event pages on the Luna platform.
3. Compile and publish a directory of 30 notable foundations and cryptocurrency clubs at top Korean universities.
4. Prepare a list of items needed for the Christmas Party.
5. Post TypeScript & Solidity Dev JDs on 30 blockchain communities

**Comment by diamondnegroni** [comment]
The priority is quite high because of the time sensitivity.  we have only 19 days to prepare,adverise, and look for sponsors. 
It would take me minimum 40 hours  to plan, prepare, and execute the event.

**Comment by 0x4007** [comment]
@diamondnegroni we are working on redeploying the bot this week with those updates from the last two months as a heads up so there might be some downtime (like now.)

The spec looks fine. Just be sure to deliver in a text document some links etc.  

The bot will price it when its up again (this should not interfere with you starting on it.)

When I have more time to think about this I might tweak the scope a bit.

**Comment by 0x4007** [comment]
@wannacfuture new error that doesn't make any sense to me https://github.com/ubiquibot/comment-incentives/actions/runs/7711668676/job/21017483843

**Comment by diamondnegroni** [comment]
Is this part functional now ? 
@pavlovcik

**Comment by 0x4007** [comment]
Let's try again! Thanks for the follow up.

**Comment by diamondnegroni** [comment]
Is it possible to change the claimable address to 0x6FEFc571fb14499112C9C34f2A68E54185760631 ?
I don't think the registered wallet is mine.

**Comment by 0x4007** [comment]
I just disabled your ability to claim from this specific issue so that the other person who owns that wallet can't get it. Let me test the new permit generation and then I'll just send you the amount because it should not work for you for this specific issue for security reasons.

**Comment by 0x4007** [comment]
Looks like the permits generate fine now! As a heads up @diamondnegroni I noticed you're using [socket](https://www.socket.tech/) to bridge. You should use the official bridge. Socket got hacked recently for a lot of money and I'm not sure if they charge extra fees on top. The official bridge is secure and charges no fees: https://bridge.gnosischain.com/

Lastly, please try and claim the new permit (it should not work) but let me know if for some reason it does. This is for thorough end-to-end testing purposes. Thank you. Here is the manual transfer for this task: https://gnosisscan.io/tx/0xace33b5746695c9569a94a935d4bfac42a16fcb6373ed135f6121eb52ff06a86

**Comment by diamondnegroni** [comment]
Socket means dapp right ?
Yes i tried to claim it and it says the reward is already claimed.

**Comment by 0x4007** [comment]
Socket is the bridge you used according to your wallet transaction history. I linked to its website in my comment for clarification. 

You can only claim one reward per GitHub issue, so yes, if you claimed one then you won't be able to claim the other. Normally we won't generate multiple permits per issue but this helped us with debugging as its still a bit rough around the edges, but mostly works finally!
