### ISSUE TITLE
Create Ubiquity Research Korea

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/partnerships#70]
As discussed in private channels, we're looking to create a local entity.

**Comment by 0x4007** [comment]
How did the meeting with the bank go?

**Comment by diamondnegroni** [comment]
They are going to visit the office as part of due diligence process  tomorrow and will decide whether they unlock all the banking functions.

**Comment by diamondnegroni** [comment]
this entity setup is taking alot more work and time than I expected because the regulation for LLC is reinforced.

**Comment by 0x4007** [comment]
> visit the office

What office? Good luck!

**Comment by diamondnegroni** [comment]
A co-working space in Gyeonggi-do offering only entity address registration, benefiting from the absence of significant corporate tax burdens, in contrast to Seoul, where establishing a corporation incurs substantial corporate taxes.
