### ISSUE TITLE
2024 ETH Seoul Sponsorship

### ISSUE THREAD

**Issue by diamondnegroni** [ubiquity/partnerships#72]
Context: 
Between March 29 and March 31, 2024, ETH Seoul will be one of the largest crypto events of EF in Korea. In light of the outcome of Ethcon 2023, it is important to strategize how to maximize the value as a sponsor at ETH Seoul. This event presents an opportunity to engage in meaningful conversations, forge valuable connections, and gain unparalleled visibility for brands and organizations. It will bring together distinguished speakers, sponsors, and key influencers, making it a mutually beneficial collaboration that amplifies a brand's impact.

**Comment by 0x4007** [comment]
We discussed offline and in a nutshell it doesn't look like it will be worth the high costs at this time. The proposed benefits was enhanced exposure to the local development scene, but, there's more cost effective ways to achieve this including, but not limited to:

1. hosting our own side event(s)
2. going to the event and actively promoting the DevPool in a more "guerrilla marketing fashion"
3. sponsoring the food/beverage and including some catchy call to action on all the mugs etc with QR code "come code. get paid. dao.ubq.fi/devpool"

**Comment by diamondnegroni** [comment]
Post-Event Gathering

-Friends & potential partner's night at Bar Orbitz
- Accommodates 30-35 guests
- Bar can be rented with no additional fee (only a minimum order requirement)

https://docs.google.com/spreadsheets/d/1trxM_AmhEutk_GV4j4Hz0lEy-SuDX3nCe_qndLpCbTc/edit?usp=sharing

Based on the current side event lists,there is only one evening event on Thursday, and no evening event on Friday.Either day will be ideal for hosting side event.

Details:
Option 1
- March 28, Thursday: Minimum expenditure of 2 million KRW, equates to approximately 2.3 glasses per person for a group of 35, with each glass costing 25,000 KRW.

Option 2
- March 29, Friday: Minimum expenditure of 3 million KRW, resulting in about 3.4 glasses per person for a group of 35, with the cost per glass remaining at 25,000 KRW.

Proposal:
- If we manage to involve Manta and DVX as sponsors and distribute the costs equally, each sponsor's contribution would range between 1,500 to 2,000 KRW.

@pavlovcik any thoughts?

**Comment by 0x4007** [comment]
> If we manage to involve Manta and DVX as sponsors and distribute the costs equally, each sponsor's contribution would range between 1,500 to 2,000 KRW.

We are incentivized to sell as much as we can to the others to reduce costs for ourselves. 

Regarding costs, I think it makes sense to talk to the bar manager first. We should also probably consider other places. Why do you think Orbit is optimal? What about places like Pine & Co, Cricket, Geranium, Le Chamber, Lupin etc?

**Comment by 0x4007** [comment]
Also since the topic is changing, it might make sense to close this as not planned and to file a new proposal.

**Comment by diamondnegroni** [comment]
The minimum order at Bar Orbitz comes directly from Jimmy, the bar manager there.

I believe that the layout, configuration, and capacity of Orbitz are the most favorable compared to other venues we've considered. If you're interested in looking into additional locations, could you please arrange a group chat with the managers of those bars?

**Comment by 0x4007** [comment]
> please arrange a group chat

Will do once it's underway. I sent some messages:

- orbit: 2M krw | 3m krw
- Le Chamber: 7m krw "daily rate"
- pine & co: not an option 
- cricket: you said it's too small so I canceled the request.
