### ISSUE TITLE
Ubiquity Night: A Gathering for DeFi Innovators, the Ethereum Community, and TypeScript Developers

### ISSUE THREAD

**Issue by diamondnegroni** [ubiquity/partnerships#76]
Proposing open a side event during Ethseoul week(March, 25- March 31)

Name of the event : Ubiquity Night: A Gathering for DeFi Innovators, the Ethereum Community, and TypeScript Developers
will be added to https://docs.google.com/spreadsheets/d/1trxM_AmhEutk_GV4j4Hz0lEy-SuDX3nCe_qndLpCbTc/edit#gid=0

Venue: Bar Orbitz
Date: Thursday, March 28, from 7:00 PM to 12:00 AM

Goals:
1. Attract TypeScript developers and IR specialists.
2. Connect with potential Series A investors.
3. Forge partnerships with DeFi protocols.

Preparation Checklist:
1. Secure Bar Orbit for the event with a budget of up to 2 million KRW from the Ubiquity DAO.
2. Set up a registration page for selective attendee approval.
3. Create promotional merchandise, such as T-shirts or bags, featuring the company's branding.
4. Extend invitations to developers who attended last year’s Christmas party.
5. Offer a special incentive: 2x on the devpool rewards
6. Hire Devs relatinoship for a week and develop a standard operating procedure to explain Dev pool to onbard typescript developers
7. Create a QR code for each devs relationship people to track performance and compensate accordingly

Budget:
1. Alcohols at Bar Orbitz : 2m krw
2. Company assets(t-shirts, bags) : 2m krw

**Comment by 0x4007** [comment]
> Name of the event : Ubiquity Night: A Gathering for DeFi Innovators, the Ethereum Community, and TypeScript Developers

> Attract TypeScript developers and IR specialists.

I think we should really highlight this in the event title, something like "Dev Cocktail Party: TypeScript & BizDevs are VIPs (hiring!)"

Or maybe something like "TypeScript dApp Cocktail Night"

> Goals:
Attract TypeScript developers and IR specialists.
Connect with potential Series A investors.
Forge partnerships with DeFi protocols.

Let's not kid ourselves with this broad set of goals. We should focus only on one to have a shot of doing it well. I think that hiring is the highest priority. The rest possibly can happen naturally but I wouldn't want to invest any dedicated resources in those. 

> Hire Devs relatinoship for a week and develop a standard operating procedure to explain Dev pool to onbard typescript developers

This seems useful. 

> Company assets(t-shirts, bags) : 2m krw

We have a ton of extra old bags to give out, I think we can get by just with those. The shirts are really expensive and I'm unsure if they are worth the cost. I'm open to trying some new swag/merchandise, but they can't be as expensive as the shirts.

**Comment by diamondnegroni** [comment]
Dev Cocktail Party: TypeScript & BizDevs are VIPs (hiring!) sounds great
I will fixed the venue at  bar Orbitz

**Comment by 0x4007** [comment]
> Hey Jimmy, we have a minimum spend of 2M KRW for Orbit as I understand. 

> I was thinking that there probably can be a better structure to make more money for orbit, for example, we just offer welcome drinks and then the guests can buy their own afterwards. What do you think?

I was starting to draft that but then realized that it doesn't make sense for me to worry about their profitability. 

I guess the easiest for us would be to run my card for $2M KRW at the beginning of the night and then everybody pays for their own drinks basically. 

I'd be happy to buy drinks for some of the earlier guests I'm talking with and hosting. But then for the later guests we just say that we already spent all the included tab. 

I think it would be fine given that we are at a literal cocktail bar.

**Comment by diamondnegroni** [comment]
are you okay with the time ?
Date: Thursday, March 28, from 7:00 PM to 12:00 AM

**Comment by diamondnegroni** [comment]
https://lu.ma/ubiquitydao
let me know if you have any comments !

**Comment by 0x4007** [comment]
> https://lu.ma/ubiquitydao let me know if you have any comments !

Can you add me for edit access?

**Comment by diamondnegroni** [comment]
which email do you want me to add
