### ISSUE TITLE
Ubiquity Dao SIde event for HK 

### ISSUE THREAD

**Issue by diamondnegroni** [ubiquity/partnerships#77]
Hong Kong Web3 Festival 
The inaugural Web3 Festival, co-hosted by Wanxiang Blockchain Labs and HashKey Group, saw over 50,000 attendees in total, 300 speakers globally, 100 exhibitors and nearly 200 side events. It’s widely acknowledged as the breaking milestone for Hong Kong’s Web3 industry.

Time: April 6 - April 9, 2024
Official Website : https://en.web3festival.org/?gad_source=1&gclid=Cj0KCQjw2a6wBhCVARIsABPeH1tE9GJ4flQjiTRY0eMsLEBtxLaXdLCqGfBFUuw-FcnOmNr7uas8DkQaAsViEALw_wcB

Side event : https://www.panewslab.com/hkweb3festival

Objective : We will open a side event to recruit type script developers  and Biz Devs

Luma Link : https://lu.ma/ouvn72nd

**Comment by 0x4007** [comment]
1. We are focusing on recruiting in Korea only for our local team. For anything international/remote its basically free to leverage our DevPool system. It doesn't make sense to spend any money to recruit internationally
2. We didn't get any results from our party.
