### ISSUE TITLE
DevCon 2024

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/partnerships#80]
https://devcon.org/en/

12-15 November 2024

### Shared accommodation notes:

Preference to be in Sukhumvit area. Location is extremely important to me. Don't want to be sitting in traffic the whole time. 

Planned Guests:
- Alex (Ubiquity)
- Ana (Ubiquity)
- Fernando (Ubiquity)
- Travis (Travis)
- Sadie (Travis)
- The two girls at the party (Presto)
- Enjeong 

### Tasks

Schedule management

Haven't fully thought these through but review #83 for general direction. 
- Booking relevant meetings
- Book/plan and have Fernando and I participate in panel/workshop discussion

**Comment by ana-0k** [comment]
Devcon side events: https://lu.ma/devcon  (not all, apparently)
 - to consider joining as a sponsor/speaker/co-host
 

> [Side Sheet 1](https://docs.google.com/spreadsheets/d/1rCkPUgaydBWaD-nPYMRfUwmkESEHHj2W3Ol26pWjr3s/edit?usp=sharing) by Caladan

> [Side Sheet 2](https://docs.google.com/spreadsheets/d/1hZ7QU_6HDxNB0vlw7JAjjath3vXOHMDtZO10J-9bnx0/edit?usp=sharing) by 13Desk

> [Crypto Nomads Club side events list](https://cryptonomads.org/DevconSideEvents2024)

**Comment by 0x4007** [comment]
I wouldn't mind speaking on any panels related to DAOs, operations, and the state of remote software development

**Comment by ana-0k** [comment]
There is a THW3 event in BKK at the same time, Nov 13-14
[**Thailand Web3 Conference** - official website](https://www.thw3.co/#application)

**! One of their exclusive partners is [Consensys](https://consensys.io) !**
Other partners are: [Maven11](https://www.maven11.com), [1kx](https://1kx.network), [EVG](https://www.evg.co)

There are options to:
- **[Become a speaker](https://zupiuv4k707.typeform.com/to/LkLMXKFh)**
- **[Become a sponsor](https://zupiuv4k707.typeform.com/to/E3sn0xOG)**

Exclusive side event for THW3: **[THW3 Welcome Party](https://lu.ma/ffg91cec)**
_"this is an invite-only event reserved for THW3 sponsors, speakers, and partners"_

---------------
Note.
Seems like a very legit event to speak at, considering their list of partners.
Will share other options below.

**Comment by 0x4007** [comment]
To be honest I'm a bit nervous to speak at a big event until I 1. Prepare the talk and practice a ton ahead of time 2. Start and get experience at smaller ones before big ones. Maybe we can make a plan for this to make speaking more part of the routine for me in the future.

**Comment by ana-0k** [comment]
[List of villas airbnb](https://www.airbnb.com/slink/7EsjP4RA)
Checked Nov 10 (Sun) - Nov 17 (Sun)
(some places look similar idk if its the same style or the same house lol need to pay extra attention when booking)

**Comment by ana-0k** [comment]
Should we create a group chat with everyone who's in the list to decide on the house?

**Comment by 0x4007** [comment]
Better if we decide and invite I think people are too indecisive. I suppose it would be prudent to collect the money up front and provide a deadline before officially booking. 

Perhaps there are some quantitative attributes we can compare like floor space, distance from city center, guest ratings etc. 

Easier to make a decision this way.

**Comment by ana-0k** [comment]
### Events with opportunity to speak:

**1.** [**How to DAO Bangkok**](https://lu.ma/p1do87lh), Nov 11 (Mon) 11am-6.30pm
_This unique experience goes beyond the basics of DAOs, diving deep into topics of coordination, regeneration, business sustainability, and the latest developments at the intersection of crypto and other industries. (also a promotion of some book about DAOs)_

**2.** [**BuildCon @ Devcon Bangkok**](https://lu.ma/b6bme40b), Nov 11 (Mon) 1pm-6pm
_Join us on November 11th for a day packed with creativity, collaboration, and cutting-edge tech. (seems targeted to students as the host is [EduDAO](https://www.edudao.io))_

----
to be continued

**Comment by ana-0k** [comment]
One more speaking opportunity, 5k is min price 
#just fyi cuz the event scale is bigger than what you aim at now.

**EVENT DETAILS**

**Hack Seasons Bangkok**, Nov 14 (Thu) 10am - 6pm
- [Official website](https://hackseasons.com)
- [Event on luma](https://lu.ma/hack_bangkok?tk=X22Zhl)
- [Deck with sponsorship options](https://docsend.com/view/bqu8ggxxym42jtur)
- good PR opportunity cuz it's run by ​​​​Metaverse Post (Mpost), there will be some media coverage
- event seems huge but I don't think panels will be overcrowded with audience
- they have a tech-oriented panel
- a lot of sponsors/speakers are infra
- might have curious engineers attending
- a bit too blockchain-themed but maybe it's just the names they wanna flash
- 5k seems like a floor price for speaking/sponsoring events (unless it's a small free one)

**Comment by 0x4007** [comment]
I think an appropriate place to start is to not pay to speak. 

Ideally I could start on some panel discussions related to DAO operations. Perhaps we should ask our network of friends to see if there are any free opportunities.

**Comment by ana-0k** [comment]
While summarizing the idea of the speech for application, I accidentally got a full outline for it from Claude lol 
Sharing just for reference, in case it gives you any new ideas.

> **1. Summary:**

The speech will addresses the current dysfunctional state of many DAOs, highlighting issues such as inefficient decision-making and poor coordination. Drawing from a decade of personal experience managing remote teams, we propose the integration of AI management systems as a solution to streamline DAO operations and improve overall efficiency. By introducing the concept of "putting the A in DAO", we suggest that AI-powered management could potentially transform DAOs into highly effective, globally distributed organizations that outperform traditional corporate structures.

> **2. Speech structure**

# The Dysfunction of DAOs and the Promise of AI Management

## Introduction
- Brief overview of Decentralized Autonomous Organizations (DAOs)
- Current state: Many DAOs struggling with operational inefficiencies

## The Problem: DAO Dysfunction
1. Lack of clear leadership and decision-making structures
2. Inefficient voting mechanisms
3. Difficulty in coordinating remote, global teams
4. Slow response to market changes and opportunities
5. Challenges in maintaining consistent engagement from members

## Lessons from a Decade of Remote Team Management
- Importance of streamlined communication
- Need for clear, actionable goals and metrics
- Value of asynchronous work processes
- Significance of cultural alignment in distributed teams

## Introducing AI-Powered DAO Management
- Concept: "Putting the A in DAO"
- AI as an impartial, always-on manager and coordinator
- Potential benefits:
  1. Faster decision-making processes
  2. Data-driven strategy formulation
  3. Improved resource allocation
  4. Enhanced member engagement through personalized interactions
  5. 24/7 operational oversight and optimization

## Implementation Challenges and Solutions
- Addressing AI bias and ensuring ethical decision-making
- Balancing AI management with human oversight
- Integrating AI systems with existing DAO infrastructure
- Training and onboarding members to work alongside AI

## The Future of DAOs
- Vision of highly efficient, globally distributed organizations
- Potential for DAOs to outperform traditional corporate structures
- Implications for the future of work and organizational design

## Conclusion
- Call to action: Embrace AI as a tool for DAO evolution
- The potential for DAOs to fulfill their promise of truly decentralized, efficient governance

**Comment by ana-0k** [comment]
**Airbnb we aim for** (5 bedroom, 6 beds):
https://www.airbnb.com/slink/v0JlE0Mz

**Dates:**
Nov 10 - Nov 16 (6 nights)

**Total price:**
4,914 USD

**Price per person:**
- If 8 ppl coming: 615 USD (831k krw)
- seems like 8 confirmed

**Deadline for $ transfer:**
Oct 13 (Sun)

If it's still available then > we book
If not available > try another airbnb OR two separate airbnbs nearby OR return money and everyone books hotels etc themselves

**Comment by 0x4007** [comment]
That deadline is very tight but okay let's try and make it happen

**Comment by 0x4007** [comment]
@transitive-bullshit @gentlementlegen you guys down?

**Comment by gentlementlegen** [comment]
Sure thing that works for me.

**Comment by 0x4007** [comment]
@gentlementlegen conversation rewards is impressively broken. I've seen a few first time errors today.

**Comment by gentlementlegen** [comment]
@0x4007 Oh I just realize this is on the main branch, will check if everything is up to date.
