### ISSUE TITLE
Create a list of target VCs and key decision makers (Strategic financing)

### ISSUE THREAD

**Issue by v4d33m** [ubiquity/partnerships#92]
Original list: 
- M12 for GitHub
- Gnosis Venture Capital
- OpenAI Startup Fund
- Coinbase Ventures
- Sequoia
- a16z Crypto
- Dragonfly Capital Partners
- Paradigm
- Union Square Ventures
- ConsenSys Ventures

Tasks: 
- Find lookalikes 
- Manually check if suitable 
- Extract partners' info via LI SN/Clay
- Enrich with emails and phone numbers
- Check if number is on telegram

**Comment by 0x4007** [comment]
@gentlementlegen no time or priority labels populated here.

**Comment by 0x4007** [comment]
@Rndquu in case you're around it would be helpful if you can fix the labels situation. I would set these two in this repo to high and 4 hours.

**Comment by v4d33m** [comment]
![photo_5364102772326263437_w](https://github.com/user-attachments/assets/455fac90-3d0c-4512-a415-965357f49383)
way too many irrelevant lookalikes, let's change task description to actually finding the right people at the right orgs.

**Comment by v4d33m** [comment]
Okay, the list of all director+ roles (Partners, CxOs, VPs) is 890. I'm going to enrich them all, validate and exclude invalid entries. Then it would take a couple of hours to manually clean up all impersonators and wannabies.  I'm going to upload interim results

**Comment by v4d33m** [comment]
also, seems like a telegram check should be a separate issue: https://chatgpt.com/share/674e2756-62c4-8008-9a41-09668558d6b3

**Comment by v4d33m** [comment]
[Find-People-from-Custom-Table-(3-December-2024)-Default-View-export-1733174305754.csv](https://github.com/user-attachments/files/17984337/Find-People-from-Custom-Table-.3-December-2024.-Default-View-export-1733174305754.csv)
890 records (before cleanup and enrichments)

**Comment by v4d33m** [comment]
<img width="1238" alt="Screenshot 2024-12-03 at 1 44 43 AM" src="https://github.com/user-attachments/assets/acaded4e-f68f-4677-8377-ac2a4783637a">
we could also check for associated whatsapp accounts

**Comment by rndquu** [comment]
> @rndquu in case you're around it would be helpful if you can fix the labels situation. I would set these two in this repo to high and 4 hours.

As far as I understand @gentlementlegen is already working on a fix in https://github.com/ubiquity-os/plugin-sdk/issues/36

**Comment by 0x4007** [comment]
@gentlementlegen  labels added but now price doesn't set

**Comment by gentlementlegen** [comment]
@0x4007 Didn't it create a `300 USD` tag?

**Comment by v4d33m** [comment]
[StrategicFinancing_CxOs-Default-View-export-1733570229744.csv](https://github.com/user-attachments/files/18048105/StrategicFinancing_CxOs-Default-View-export-1733570229744.csv)

Here are the results. Cleaned up list, containing 382 records, fully enriched with VALID emails only and mobile phones. 
 
Number of Clay credits spent: 3404
