### ISSUE TITLE
Create a list of target DAOs (Pilots) 

### ISSUE THREAD

**Issue by v4d33m** [ubiquity/partnerships#93]
Original list: 
- Gnosis
- Uniswap
- Curve
- Paradigm
- Synthetix
- Optimism
- Aave
- Compound
- Yearn
- dYdX

Tasks to be done: 
- Describe DAO qualification criteria
- Do lookalike research in clay 
- Manually check if they qualify 
- Extract decision makers from LI SN/Clay 
- Enrich with phone / email info
- Check if they on telegram

**Comment by v4d33m** [comment]
@0x4007 Curve - is it curve.fi ? or curve.com?

**Comment by v4d33m** [comment]
[Find-People-from-Copy-of-Custom-Table-(3-December-2024)-Default-View-export-1733177537611.csv](https://github.com/user-attachments/files/17984546/Find-People-from-Copy-of-Custom-Table-.3-December-2024.-Default-View-export-1733177537611.csv)
this list is much smaller - less than 140 records. Enrichments launched, i will report back with the cleaned lists tomorrow

**Comment by 0x4007** [comment]
Curve.fi

**Comment by v4d33m** [comment]
Here is the list of Pilot DAOs and all people scraped from LI SN by Clay. 
[People-from-PilotDAOs.csv](https://github.com/user-attachments/files/17998518/People-from-PilotDAOs.csv)
