### ISSUE TITLE
Initialize CRM

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/partnerships#95]
Picking up from where we left off with Matt + Brandon on our previous outreach efforts, we need to aggregate all of the copywriting and contact information and organize into a brand new CRM for our new Q1 2025 outreach initiatives. 

I will append the chat export from them here when its available. 

- Use HubSpot
- Be sure to deduplicate.

**Comment by 0x4007** [comment]
Just sent you the previous group chat's contents with all the data and logins on Telegram!

**Comment by minhyeong112** [comment]
I've read through all the chat history and have consolidated the data into a google sheet (for the contacts) and a google doc (for the copy). Standing by for @v4d33m to set up hubspot as part of #97 and I will upload and deduplicate.

**Comment by 0x4007** [comment]
@minhyeong112  how's this project coming along?

Also @gentlementlegen  we should improve support for scenarios without pull requests

**Comment by gentlementlegen** [comment]
@0x4007 You can disable that per repo with the options in the configuration file.

**Comment by 0x4007** [comment]
I can't from mobile, I also off hand don't know which properties to configure, but I already switched one property related to this that you recommended the other day but that's not enough it seems

**Comment by minhyeong112** [comment]
> how's this project coming along?

I've done part 1 (aggregating all the info), just waiting on the CRM login for part 2 (shoving it into CRM).

Just got your cloudflare email and verified my email.

Meeting @v4d33m in 3 hours to see what accounts he has set up.

Should be able to proceed and complete quickly if the email logins work as expected.

**Comment by minhyeong112** [comment]
@0x4007 can you plz provide an email to @v4d33m so that he can add you to the hubspot?

I cannot finalize this task until that is done.

**Comment by 0x4007** [comment]
Yes I sent a dm

**Comment by minhyeong112** [comment]
Hubspot CRM initialized with all contacts from chat export.  Task complete. 
![image](https://github.com/user-attachments/assets/cc307e1b-1dca-4796-8cae-08a0246892d3)
![image](https://github.com/user-attachments/assets/36a918bd-7f15-4c41-89e1-c75ddd7d2491)
