### ISSUE TITLE
Ubq.fi Martech stack 

### ISSUE THREAD

**Issue by v4d33m** [ubiquity/partnerships#97]
Choose, approve budget and set up accounts for the following systems: 
- CRM, proposed Hubspot
- Prospecting, proposed Clay 
- Domain / SMTP providers, proposed AutomateInbox, InfraInbox, Outreach2day 
- Email warmup tool, proposed Smartlead.ai 
- Email outreach tool, proposed Smartlead.ai 
- LI outreach tool, proposed HeyReach.io 
- Call / whatsapp / telegram platform - some research required here 

Estimated - 2 hours
FYI potential blockers @0x4007 - call/whatsapp registration might require business presence. do we have a legal entity that we could use?

**Comment by 0x4007** [comment]
> do we have a legal entity that we could use?

Yes we have a BVI

>  telegram platform

nReach?

**Comment by v4d33m** [comment]
nReach looks too pricey for the use case

**Comment by 0x4007** [comment]
@ubiquityos @gentlementlegen do you think you can explain how to and/or can you disable the pull request requirement for tasks in this repository?

**Comment by v4d33m** [comment]
yep, doing pull requests for bizdev tasks looks like a waste of time - we don't really pull them into codebase.

**Comment by v4d33m** [comment]
Re: telegram, potential solutions (trial required): 

https://respond.io/integrations/telegram
https://www.niswey.com/telegram-hubspot-integration-niswire

**Comment by gentlementlegen** [comment]
@0x4007 you can set the following item to false in the configuration: https://github.com/ubiquity-os-marketplace/daemon-disqualifier/blob/231931632e9d94802dc2a103628ac71ec54b33dd/src/types/plugin-input.ts#L90

**Comment by 0x4007** [comment]
@gentlementlegen set https://github.com/ubiquity/business-development/commit/bbe793bc573488f9e26899479541a3f64f14228a

**Comment by v4d33m** [comment]
**Budget:** 

- CRM, Hubspot Starter, 3 seats ($20 per seat monthly or $12-15 for annual commit) (@0x4007 , @minhyeong112 , @v4d33m ) = $60 per month or $504 per year paid upfront
- Prospecting, Clay, Starter plan - $149 per month - 2000 credits, should be enough for 200-300 fully enriched leads per month. 
- Domains: 
-- Google (InboxAutomate): $15 per domain per year + $4 per inbox per month (no minimum order). - more than 50% of our target audience use g-suite. I propose to purchase 3 domains ($45 per year) and create 3 mailboxes in each = $36 per month = $81 (first month)
-- Outlook (InfraInbox): $15 per domain per year + $1 per inbox per month (minimum 2 domains and 50 mailboxes per domain). = $30 per year + $100 per month _After checking our list of Strategic Financing leads, i've realised that 0% of our target audience is using outlook, which is amazing - let's pass on that_ 
-- SMTP (outreach2day) $12 per domain per year + $2.5 per mailbox per month (minimum 3 domains x 4 mailboxes) = $36 per year + $30 per month = $66 (first month) 
- Email warmup and sequencing - Smartlead.ai - $39 / mo
- HeyReach - 2 accounts (Mig and Alex) x $79 per month = $158 / mo
- Respond.io (telegram integration) - $79 / mo (5 users included) 

**Total for the first month = $632**

![Hubspot-monthly](https://github.com/user-attachments/assets/4de6343c-47cc-47da-bbb4-290cb9c10efc)
![Hubspot-annually](https://github.com/user-attachments/assets/9791e735-f560-4088-9587-f883999504bc)
![Clay](https://github.com/user-attachments/assets/c6689ecf-866a-4f83-a4ab-97c3f16047c2)
![Smartlead - Basic](https://github.com/user-attachments/assets/841e4d19-59dd-4b52-9838-603968f7783f)
![HeyReach](https://github.com/user-attachments/assets/f342a8ab-f172-4a02-9aaf-b98d3c4bc213)
![Respond io](https://github.com/user-attachments/assets/4c1e037e-5484-4964-be4d-9c6c46b94a0a)

**Comment by 0x4007** [comment]
> Total for the first month = $632

https://gnosisscan.io/tx/0x87978084b577a578d235b8e6ce259abe06263af9f860e03a2bab047fbf953504

> or $504 per year paid upfront

We should be planning for the long run though. Outreach for Ubiquity should continue in perpetuity

--- 

I'm about to turn in for the night but we're tight on timelines to get things moving so I want to focus on getting us on track before dialing into micro cost optimizations.

**Comment by v4d33m** [comment]
let me get annual prices for other tools as well

**Comment by v4d33m** [comment]
Hubspot = $504
Clay = $1608
Smartlead = $390

As for other tools - either annual plans are not available, or I'm not that sure that we are going to use them for so long.

**Comment by v4d33m** [comment]
also - calling tool is still in question. 

I propose to start with domains and email warmup - as these tasks have the longest lead time. And CRM set up as this is just at the core of all other activities.

**Comment by 0x4007** [comment]
I think any domains can be purchased as long as they are roughly referencing the Ubiquity name. @v4d33m Are you or Miguel setting up the CRM? Seems that he's waiting on you before importing the contact data.

**Comment by v4d33m** [comment]
I will send an invite, set up the initial pipeline and will onboard Miguel into it. We will do it over 1 hr meeting tomorrow so he could shadow me. The rest (adding leads, populating info, bringing that system up to the speed) - he will be able to do it on his own

**Comment by v4d33m** [comment]
I need email addresses to send invites for @0x4007 and @minhyeong112

**Comment by v4d33m** [comment]
Accounts registered, please accept @0x4007 
<img width="201" alt="Screenshot 2024-12-08 at 1 14 22 PM" src="https://github.com/user-attachments/assets/0be1cc53-a037-44f5-94d0-6c22863a9eaf">
<img width="368" alt="Screenshot 2024-12-08 at 2 03 22 PM" src="https://github.com/user-attachments/assets/6c7f851b-d848-4bf6-8a86-41879ecfaec8">
<img width="201" alt="Screenshot 2024-12-08 at 2 17 42 PM" src="https://github.com/user-attachments/assets/f28d110b-6f52-461e-a99c-92808266cfa9">
<img width="293" alt="Screenshot 2024-12-08 at 12 33 29 PM" src="https://github.com/user-attachments/assets/a04e6f40-96b8-4e2f-9982-f86ea2213324">

**Comment by 0x4007** [comment]
@gentlementlegen you got paid $15 for a 0 relevance comment. There's a bug in the calculation. I guess we should not add the formatting score separately. We should do it the old way and just multiply all of it against relevance. 

Also we really need to fix the specification multiplier to not be affected by priority level.

**Comment by gentlementlegen** [comment]
@0x4007 It is not a bug, relevance only applies to the comments not the formatting, that was changed quite some time ago when you wanted the base price of html elements to not be affected by the relevance. It used to be applied to the whole result before.

Yes I will look into it.
