### ISSUE TITLE
Domain and mailbox registration and warmup

### ISSUE THREAD

**Issue by v4d33m** [ubiquity/partnerships#99]
- Purchase and register domains 
- Setup SMTP and Google email services
- Set up MX, DMARC, DKIM records 
- Set up redirect 
- Set up mailboxes 
- Initiate warmup 
**- DoD: 3 Domains for SMTP (4 mailboxes/ea), 3 Domains for Google (3 mailboxes/ea), clean MXTOOLBOX report**  
 
Estimate - 2 hrs

**Comment by v4d33m** [comment]
+ connect emails to Smartlead

**Comment by 0x4007** [comment]
Consider getting outlook as well. It's super common in corporate

**Comment by v4d33m** [comment]
@0x4007 i have purchased +2 outlook domains with 3 mailboxes ea
<img width="539" alt="Screenshot 2024-12-10 at 1 56 18 AM" src="https://github.com/user-attachments/assets/2d94e0be-fe3b-4590-b00c-e11be5da5287">

**Comment by v4d33m** [comment]
<img width="958" alt="Screenshot 2024-12-10 at 1 57 55 AM" src="https://github.com/user-attachments/assets/c25ce089-14e6-4da3-ba56-409cd1c9568f">

@0x4007 please extend deadline by 48 hours - we are waiting for DNS/MX records to update (domain delegation)

**Comment by v4d33m** [comment]
domains for SMTP are set, mailboxes are warming up
<img width="1168" alt="Screenshot 2024-12-10 at 2 03 41 AM" src="https://github.com/user-attachments/assets/d1b4ce21-a550-4830-b922-8dfe2011c013">
<img width="1159" alt="Screenshot 2024-12-10 at 2 04 31 AM" src="https://github.com/user-attachments/assets/4b7ccc20-e3b6-46cf-8254-9e10d06e9e29">

**Comment by v4d33m** [comment]
Interim mxtoolbox report, working with service providers on the following issues:  
<img width="1416" alt="Screenshot 2024-12-10 at 2 07 42 AM" src="https://github.com/user-attachments/assets/cea7f67f-d3b3-4ebe-b247-497fc77f1396">
<img width="1413" alt="Screenshot 2024-12-10 at 2 10 25 AM" src="https://github.com/user-attachments/assets/8159aefb-52dc-4ae6-9d9f-f040c117e86a">
<img width="1421" alt="Screenshot 2024-12-10 at 2 12 19 AM" src="https://github.com/user-attachments/assets/a9a7c4a1-6b52-4255-92fc-ed1cec00502e">
<img width="1426" alt="Screenshot 2024-12-10 at 2 12 50 AM" src="https://github.com/user-attachments/assets/062ca2ac-2e1f-451b-9f28-4d88f61e3031">
<img width="1418" alt="Screenshot 2024-12-10 at 2 13 15 AM" src="https://github.com/user-attachments/assets/ccb2db39-0951-43dd-9b3f-41d3be003c34">

**Comment by 0x4007** [comment]
> @0x4007 please extend deadline by 48 hours - we are waiting for DNS/MX records to update (domain delegation)

As long as you provide regular updates the deadlines shouldn't affect you.

**Comment by 0x4007** [comment]
@gentlementlegen can you double check the pull requirement here? v4d33m shouldn't have been unassigned due to the comments.

**Comment by v4d33m** [comment]
Here are some updates: 
Warmup enabled for Gmail and Outlook mailboxes 
![Screenshot 2024-12-11 at 11 58 37 AM](https://github.com/user-attachments/assets/78947b2b-92a5-4955-9e1c-3285f182abe5)
![Screenshot 2024-12-11 at 11 58 49 AM](https://github.com/user-attachments/assets/fa961001-24e7-4e1b-8cea-91889feff8d1)

**Comment by v4d33m** [comment]
emails connected to smartlead

**Comment by v4d33m** [comment]
we have clean MX record for ubiquti.com (outlook) and ubqfi.com (SMTP)
![Ubiquti 2024-12-11 at 11 55 36 PM](https://github.com/user-attachments/assets/18f3501f-134a-40e3-88c8-bccafead3f73)
![ubqfi com 2024-12-12 at 12 03 01 AM](https://github.com/user-attachments/assets/9469308d-f489-408e-828a-0ba09dff9d2b)

DMARC/DKIM/MX fixed for  Ubquity-dao.com and ubquty.com, just waiting for the domain to mature a bit and get out of SEM FRESH blacklists 
![ubquity-dao com 2024-12-12 at 12 02 14 AM](https://github.com/user-attachments/assets/129db283-e371-4a82-82a5-98294de088a3)
![ubquty com 2024-12-12 at 12 01 26 AM](https://github.com/user-attachments/assets/37fdc3bc-0e30-4017-8546-72e58c4d2354)

Still working on ubquitydao.com, ubiquity-dao.com and ubqfy.com. I've reached out to the upstream provider support to resolve the issues. 
![ubqfy com 2024-12-11 at 11 59 18 PM](https://github.com/user-attachments/assets/5627f6cb-c6b2-4dc6-8444-f9b9bc1d15d5)
![ubquitydao com 2024-12-11 at 11 58 58 PM](https://github.com/user-attachments/assets/979bfcf0-2455-493d-ab6a-4e31c415d6f6)
![ubiquity-dao com 2024-12-12 at 12 00 21 AM](https://github.com/user-attachments/assets/77e3c025-6349-40f0-abe2-ce0476f6ca6b)

**Comment by v4d33m** [comment]
Ubiquity-DAO is clean 
https://mxtoolbox.com/emailhealth/ubqtidao.com/
<img width="1412" alt="Screenshot 2024-12-12 at 12 38 09 PM" src="https://github.com/user-attachments/assets/1da0e404-c921-44a4-8a35-890180c6b03e" />

waiting for 
https://mxtoolbox.com/emailhealth/ubqfy.com/ and https://mxtoolbox.com/emailhealth/ubqtidao.com/ 
please extend the deadline

**Comment by 0x4007** [comment]
Can you list all the domains? They should not be spelled wrong that looks sketchy.

**Comment by v4d33m** [comment]
That was done intentionally - we don't have that many options with current domain availability. From deliverability standpoint we should stick to .com domains and that's what we have:
- ubiquity-dao.com - GMAIL
- ubqfy.com - GMAIL
- ubqtidao.com - OUTLOOK 
- ubquti.com - OUTLOOK
- ubqfi.com - SMTP 
- ubquity-dao.com - SMTP
- ubquty.com - SMTP

we will start our email campaigns with a set of 3 domains, 1 pear each ESP respectively. Other domains we keep as a contingency for an unfortunate but very likely event of a domain being blacklisted.

**Comment by 0x4007** [comment]
I'm really not on board with misspelled domains. Last time some examples of domains we did was like 

getubiquitydao.con
goubiquitydao.com
startubiquitydao.com

DAO optional 

Etc

**Comment by v4d33m** [comment]
okay, looks like i misunderstood your comment here: https://github.com/ubiquity/business-development/issues/97#issuecomment-2525375494
would you like me to buy other domains? 

At the moment the email is delivered into inbox it very much depends on the copy, rather than domain name. Go-Ubiquity-DAO also would not look exactly as ubq.fi, but if you are not on board - let's get some more. By the way, are we good with: 
ubiquity-dao.com - GMAIL
ubqfy.com - GMAIL
ubqfi.com - SMTP
? 

Please let me know how would you like to proceed.

**Comment by v4d33m** [comment]
by the way, did you also notice that all these domains redirect to ubq.fi ? that's how you are usually making sure that if someone is having a second thought on the person, who are sending an email - they could check the domain. Anyway, let me know what should i do next.

**Comment by 0x4007** [comment]
Yes let's get new domains that are not misspelled but can be referencing Ubiquity DAO or its products (e.g. UbiquityOS)

**Comment by 0x4007** [comment]
According to the follow up schedule it disqualified Vadim too early. Can we disable the pull request dependency @gentlementlegen

**Comment by v4d33m** [comment]
two new domains for Outlook purchased: 
- tryubiquity.com
- runubiquity.com
6 mailboxes added. 

![photo_5411190212484264296_w](https://github.com/user-attachments/assets/2370edea-9b1f-4caf-bd4e-0ff55a5c15e4)

Proceeding to connecting to Smartlead, setting up DMARC, DKIM and MX records

**Comment by v4d33m** [comment]
Domains are all set up (ignore SEM FRESH, that's normal for new domains), emails are connected and getting warmed up! Should be all warmed up and ready to send out emails by the 2nd week of January! @0x4007 please accept the task 

<img width="1177" alt="Screenshot 2024-12-21 at 1 38 38 PM" src="https://github.com/user-attachments/assets/05eddfa8-dc78-4bf0-81f1-8fa49c1af4f3" />
<img width="1429" alt="Screenshot 2024-12-21 at 1 38 47 PM" src="https://github.com/user-attachments/assets/876f7b91-d178-4d59-8349-995754cdbde9" />
<img width="1428" alt="Screenshot 2024-12-21 at 1 38 56 PM" src="https://github.com/user-attachments/assets/1077b696-83c2-4639-b87e-f3f5433245e5" />

**Comment by v4d33m** [comment]
no bonus calculation here?

**Comment by gentlementlegen** [comment]
Let me fix it in a bit.
